// descrption
// Alex English

#include <stdio.h>
#include <stdbool.h>
#include "seatingGen.h"
#include "reading.h"
#include "writing.h"

#define TARGETFILE "SeatPlan.bin"
#define MAXSEATS 12

// Function that will print off the interface
void interface() {
	printf("To choose a function, enter its letter label :\n");
	printf("a) Show number of empty seats\n");
	printf("b) Show list of empty seats\n");
	printf("c) Show alphabetical list(by passenger name) of seats\n");
	printf("d) Assign a customer to a seat assignment\n");
	printf("e) Delete a seat assignment\n");
	printf("f) Quit\n\n");
}

// Switch case that will read the input and activate the matching function
bool interfaceInput(char input[1]) {
	int inputValue = *input; // Converts the input into an int so I can use a switch case
	// switch case to select function
	switch (inputValue)
	{
	case 97: // a) Show number of empty seats
		emptySeatsTotal(TARGETFILE);
		return 1;
	case 98: // b) Show list of empty seats
		emptySeatsList(TARGETFILE);
		return 1;
	case 99: // c) Show alphabetical list(by passenger name) of seats
		return 1;
	case 100: // d) Assign a customer to a seat assignment
		assignSeat(TARGETFILE);
		return 1;
	case 101: // e) Delete a seat assignment
		unassignSeat(TARGETFILE);
		return 1;
	case 102: // f) Quit
		exit(0);
	// A debug function incase the list is corrupted or does not exist and a new blank one needs to be made. 
	// You should never have to use this but it was to useful to get rid of.
	case 126:
		generateSeatingPlan(TARGETFILE);
		return 1;
	default: // A valid option is not given
		printf("\ninvalid\n");
		return 0;
	}
}

int main(void) {
	bool accepetedcommand = 1;
	while (1) {
		// Will only print interface after a valid command was given to prevent spamming the interface in console
		if (accepetedcommand) {
			interface();
			accepetedcommand = 0;
		}
		char input[1];
		printf("> ");
		gets(input);
		accepetedcommand = interfaceInput(input);
	}
}

// Function that will print an error if the target file can not be found
void ioError(char* targetFile) {
	fprintf(stderr, "Error, could not access source file for reading/writing: %s\n", targetFile);
	printf("A new blank source file can be generated by typeing '~' into the interface prompt\n");
	printf("Warning: This will overwrite an existing file. Do not use unless one does not already exist or has become unreadable.\n\n");
}